# Generated by Django 5.2.6 on 2025-09-08 16:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('capacidade_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacidade_m3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cep_origem', models.CharField(blank=True, max_length=9)),
                ('endereco_origem', models.CharField(blank=True, max_length=255)),
                ('cidade_origem', models.CharField(blank=True, max_length=100)),
                ('estado_origem', models.CharField(blank=True, max_length=2)),
                ('ponto_origem_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('ponto_origem_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('cep_destino', models.CharField(max_length=9)),
                ('endereco_destino', models.CharField(max_length=255)),
                ('cidade_destino', models.CharField(max_length=100)),
                ('estado_destino', models.CharField(max_length=2)),
                ('ponto_destino_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('ponto_destino_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume_m3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ROTA', 'Em Rota'), ('ENTREGUE', 'Entregue'), ('FALHOU', 'Falhou')], default='PENDENTE', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('veiculo_alocado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to='api.veiculo')),
            ],
        ),
    ]
