# Generated by Django 5.2.6 on 2025-09-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='ponto_destino_lat',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='ponto_destino_lng',
        ),
        migrations.AddField(
            model_name='entrega',
            name='cep_origem',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='entrega',
            name='cidade_origem',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='entrega',
            name='endereco_origem',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='entrega',
            name='estado_origem',
            field=models.CharField(default='PR', max_length=2),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='estado_destino',
            field=models.CharField(default='PR', max_length=2),
        ),
    ]
