# Generated by Django 5.2.6 on 2025-09-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_remove_entrega_ponto_destino_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='ponto_destino_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='entrega',
            name='ponto_destino_lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='entrega',
            name='ponto_origem_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='entrega',
            name='ponto_origem_lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='cep_origem',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='cidade_origem',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='endereco_origem',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='estado_destino',
            field=models.CharField(default='SP', max_length=2),
        ),
    ]
