# Generated by Django 5.2.6 on 2025-09-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_entrega_ponto_destino_lat_entrega_ponto_destino_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='route_geometry',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
